### ISSUE TITLE
Getting errors when i launched gazebo

### ISSUE THREAD

**Issue by hamdi-sharaf** [koichirokato/gazebo_sensor_ros2#1]
Firstly, thanks for this work.
I did exactly as you explained. But when i launch gazebo i got error as photo shown

![Screenshot from 2023-07-27 11-53-51](https://github.com/koichirokato/gazebo_sensor_ros2/assets/48509197/289ee12a-f1c4-4028-ae7e-5efa06d1d318)

**Comment by koichirokato** [comment]
Hi! 
It seems Issue of launching gazebo.
Could you try this?

```
source /usr/share/gazebo/setup.bash
```

And if this will not work, please tell me your environment (ROS and Gazebo version).

**Comment by hamdi-sharaf** [comment]
Yah its work now, thank you so much @koichirokato

**Comment by hamdi-sharaf** [comment]
and this what i got when i launched only world on gazebo 
![Screenshot from 2023-07-31 20-13-38](https://github.com/koichirokato/gazebo_sensor_ros2/assets/48509197/40bebb65-721d-4284-9bc3-b6182c893d37)
